site_name: UNITN BSc
site_url: https://yifen9.github.io/UNITN.BSc
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji

nav:
  - Home: index.md
  - Courses: courses.md