site_name: Bachelor of Computer Science
site_url: https://your-username.github.io/UNITN.BSc # Replace it by your own site

repo_name: UNITN BSc
repo_url: https://github.com/your-username/UNITN.BSc # Replace it by your own repo site

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: custom   # Custom color defined in extra CSS
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.jpg       # UniTrento logo image (recommend PNG with transparency)
  favicon: assets/favicon.png
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

# Custom CSS and JS for layout + logo effects
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
  - overrides/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - overrides/extra.js

# Markdown features
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - meta
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      permalink: true

# Plugins
plugins:
  - awesome-pages
  - search

nav:
  - Home:
    - index.md
