site_name: Bachelor of Computer Science
site_url: https://yifen9.github.io/UNITN.BSc

repo_name: UNITN BSc
repo_url: https://github.com/yifen9/UNITN.BSc

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: custom   # Custom color defined in extra CSS
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.jpg       # Your UniTrento logo image (recommend PNG with transparency)
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - content.code.copy

# Custom CSS and JS for layout + logo effects
extra_css:
  - overrides/extra.css
extra_javascript:
  - overrides/extra.js

# Markdown features
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true

# Plugins
plugins:
  - search
  - awesome-pages

nav:
  - Home:
    - index.md